### PR TITLE
Working Skip support

### PR DESCRIPTION
**Pull request by embray**
Unfortunately the display of skipped tests was not working for me with recent versions of nose.  I can go into the details, but what it comes down to is that the way the `SkipPlugin` works, as a subclass of `ErrorClassPlugins`, it consumes skipped tests such that no other plugin can even know they ever existed--the `addSkip` method is never called either.

There are several ways to work around this, but the simplest I can think of is to simply disable the skip plugin and handle `SkipTest` exceptions directly in this plugin.

This also adds a total of how many tests were skipped, and a bar to the results. The Example notebook is updated to demonstrate the new capability.

I also have a branch at https://github.com/iguananaut/ipython_nose/tree/css-tweaks that was branched off from this change which adds some prettier (IMO) result bars. But I'll defer that until and unless this PR is accepted; otherwise I can tweak it to not depend explicitly on this PR.

### CODE REVIEW

**Comment by eloraburns** [comment]
This looks awesome! I was wondering where the skiptests went. :/

I'll try to give it a poke and merge it in in the next day or two. Thanks!

**Comment by embray** [comment]
Oh I should have added, here's a sample of how the new CSS works in my other branch: http://nbviewer.ipython.org/urls/gist.github.com/raw/4281956/e1bc4f2b74b683a2766e791402fda645b076ec62/nb-nose-example.ipynb

**Comment by eloraburns** [comment]
Looks great, and I _love_ the new CSS look. Thanks!

**Comment by embray** [comment]
Great, thanks. I think this an important project so I'll see what I can do if anything else comes up.

**Comment by eloraburns** [comment]
Yup, there'll be a chunk of work coming up with respect to https://github.com/ipython/ipython/pull/2518 . At some point I'll also submit the thing wholesale to ipython so it comes with the stock ipython install. :) (and that might require its own work, too)

**Pull request merged**
